# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

[framework]
simple_name = "cupy"
full_name = "cupy"
prefix = "cp"
postfix = "cupy"
class = "CupyFramework"
arch = "gpu"

[[framework.postfixes]]
impl_postfix = "cupy"
description = "cupy"
