# SPDX-FileCopyrightText: 2022 - 2023 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

[benchmark]
name = "Needleman-wunsch Algorithm"
short_name = "nw"
relative_path = "nw"
module_name = "nw"
func_name = "nw"
kind = "microbenchmark"
domain = "Sequence Matching"
input_args = [
    "input_itemsets",
    "reference",
    "max_rows",
    "max_cols",
    "penalty",
    "result"
]
array_args = [
    "input_itemsets",
    "reference",
    "result",
]
output_args = [
    "result",
]

[benchmark.parameters.S]
grid_size = 16
penalty = 3
seed = 7

# [benchmark.parameters.M16Gb]
# grid_size = 1024
# penalty = 3
# seed = 7

# [benchmark.parameters.M]
# grid_size = 1024
# penalty = 3
# seed = 7

# [benchmark.parameters.L]
# grid_size = 1024
# penalty = 3
# seed = 7

[benchmark.init]
func_name = "initialize"
types_dict_name="types_dict"
precision="double"
input_args = [
    "grid_size",
    "penalty",
    "seed",
    "types_dict",
]
output_args = [
    "input_itemsets",
    "reference",
    "max_rows",
    "max_cols",
    "result"
]
